### ISSUE TITLE
[Bug]: Python (affects only the for ... in inside comprehensions)

### ISSUE THREAD

**Issue by YuCao16** [HiPhish/rainbow-delimiters.nvim#16] opened 2023-07-22 10:56 UTC
### Neovim version

0.10.0

### Language affected

python

### Description

```Text
As stated in the title, I know this is not a problem with the plugin. Are there any temporary solutions?
```

**Comment by HiPhish** [comment] 2023-07-22 15:24
Can you please elaborate what exactly the issue is? Where is the problem when
you have an expression like this?

```python
[x for x in [y for y in [z for z in zs]]]
```

**Comment by YuCao16** [comment] 2023-07-22 18:32
> 

Very Shiny:
![Screenshot from 2023-07-22 19-30-39](https://github.com/HiPhish/rainbow-delimiters.nvim/assets/62466929/2820441d-34f4-47c9-a64d-f435311c3372)

**Comment by HiPhish** [comment] 2023-07-22 19:02
Look normal to me. What exactly do you want changed? Do you want the `for` not to be highlighted? Are the colours wrong?

**Comment by YuCao16** [comment] 2023-07-22 19:25
> Look normal to me. What exactly do you want changed? Do you want the `for` not to be highlighted? Are the colours wrong?
> 

Yes, all for and in should be purple.

**Comment by HiPhish** [comment] 2023-07-22 19:31
Yeah, I think it was too presumptuous of me to highlight the keywords as well. Update to the latest `master`, they should now have their normal highlighting.

**Comment by YuCao16** [comment] 2023-07-22 21:03
Perfect, Thanks!

**Comment by HiPhish** [comment] 2023-07-24 21:09
Closing this as complete

**Closed by HiPhish** 2023-07-24 21:09 UTC
Labels: bug
