### ISSUE TITLE
[Bug]: delimiters only colored on startup

### ISSUE THREAD

**Issue by tim-hilt** [HiPhish/rainbow-delimiters.nvim#9] opened 2023-07-11 14:12 UTC
### Neovim version

0.9.1

### Language affected

Lua

### Description

When I open nvim, I see all delimiters colored as expected. However as soon as I type something, the delimiters are not colored automatically. Here's a screenshare of how that looks:

https://github.com/HiPhish/rainbow-delimiters.nvim/assets/16037579/2135c541-6fda-4090-b838-66bc1924e77d

You can find where I configure rainbow-delimiters here: https://github.com/tim-hilt/nvim/blob/29956421878f559581c3c6509b43810c12d97582/init.lua#L74-L76

I basically use the default configuration.

**Comment by HiPhish** [comment] 2023-07-11 17:02
This is a duplicate of #2, please subscribe to that issue for updates. I am closing this one as duplicate.

There is something weird going on because I experience the problem on a per-file basis. The C++ highlight test file for example does not updated in real time, but if I create a minimal C++ file it works flawlessly. That makes this issue quite tricky.

In the meantime you can execute `:edit`, which will trigger a full re-draw. It's not real time, but it is better than nothing.

**Closed** 2023-07-11 17:02 UTC
Labels: bug

**Comment by tim-hilt** [comment] 2023-07-11 17:07
Thanks for the information! I'll subscribe to the mentioned issue then.
